Create Chrome plugin - Init
rtbf-ir/chrome-plugin pull request #1
Opened 2022-04-14 23:31 UTC by dashtaki

2022-04-14 23:38 UTC, dashtaki commented
The icon won't change in order to show the difficulty on the page load, User should click on the icon to see more details and then the icon will change too. This behavior will be added soon.

2022-04-16 02:06 UTC, Matin-B requested changes
با توجه به اینکه سرویس های ثبت شده صفحه جداگانه ای در وب‌سایت ندارند فکر می‌کنم بهتر باشه دکمه "حذف حساب کاربری" هم نمایش داده بشه.
همچنین به دلیل تغییر آدرس ریپازیتوری بهتر هست در تمام بخش ها از آدرس جدید(rtbf-ir) بجای amirshnll استفاده کنیم.

2022-04-16 22:24 UTC, dashtaki commented
> با توجه به اینکه سرویس های ثبت شده صفحه جداگانه ای در وب‌سایت ندارند فکر می‌کنم بهتر باشه دکمه "حذف حساب کاربری" هم نمایش داده بشه. همچنین به دلیل تغییر آدرس ریپازیتوری بهتر هست در تمام بخش ها از آدرس جدید(rtbf-ir) بجای amirshnll استفاده کنیم.

ممنون از کامنتتون .دکمه حذف  حساب کاربری در صورتی که لینک حذف وجود داشته باشد نمایش داده میشه . همچنین لینکها به رپو جدید تغیر پیدا کرد.

2022-04-17 00:09 UTC, Matin-B approved these changes

2022-04-17 00:10 UTC, Matin-B commented
> 

سپاس از شما بابت اعمال تغییرات و مشارکتتون.

2022-04-19 20:58 UTC, amirshnll reviewed
Thanks for your contribution to the right to be forgotten directory.

2022-04-19 20:58 UTC, merged